baseURL = "/"
languageCode = "en-us"
title = "Wilson Villalba"
description = "Litigios."
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Wilson Villalba"
    description = "Litigios"
    logo = "favicon/android-chrome-192x192.png"
#   twitterAuthor = "@TheRealMe"
    githubUsername = "FriendsAtDawn"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Playfair Display" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url  = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Notas sobre D."
    weight = 2

# [[menu.main]]
#   url = "/files/"
#   name = "Archivos"
#   weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 7

[[menu.main]]
    url = "/plra/"
    name = "PLRA"
    weight = 4

[[menu.main]]
    url = "/links/"
    name = "Links"
    weight = 5

#  [[menu.main.plra]]
#  url = "/plra/"
#  name = "PLRA"
#  weight = 1

    
#  [[menu.main.loquesea]]
#  url = "/loquesea/"
#  name = "loquesea"
#  weight = 2
    
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url  = "mailto:page@wilson.villalba.is"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
   url = "https://github.com/FriendsAtDawn"
   name = "fab fa-github"
   weight = 2

# [[menu.icon]]
#   url = "https://twitter.com/TheRealMe/"
#   name = "fab fa-twitter"
#   weight = 3
  
# [[menu.icon]]
#   url = "https://www.linkedin.com/in/nathan-day-59b48435/"
#   name = "fab fa-linkedin"
#   3 weight = 4
  
# [[menu.icon]]
#   url = "https://www.stackoverflow.com/users/5878751/nate"
#   name = "fab fa-stack-overflow"
#   weight = 5
